name: Java CI with Maven
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
    
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@v1
        with:
            chromedriver-version: '88.0.4324.96'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name:  Install Google Chrome # Using shell script to install Google Chrome
        run:   |
                chmod +x ./scripts/InstallChrome.sh
                            ./scripts/InstallChrome.sh 
      - name: Build with Maven
        run: mvn verify --file pom.xml
      - name: chromedriver
        run: |
          CHROME_VERSION=$(google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1) \
          && CHROMEDRIVER_RELEASE=$(curl --location --fail --retry 3 http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}) \
          && curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_RELEASE/chromedriver_linux64.zip" \
          && cd /tmp \
          && unzip chromedriver_linux64.zip \
          && rm -rf chromedriver_linux64.zip \
          && sudo mv chromedriver /usr/local/bin/chromedriver \
          && sudo chmod +x /usr/local/bin/chromedriver \
          && chromedriver --version \
          && ls
      - name: Start Selenoid Server
        uses: Xotabu4/selenoid-github-action@v2
        with:
            selenoid-start-arguments: --browsers 'chrome' --last-versions 1

      - name: Junit tests
        run:  | 
          mvn -Dtest=my_first test
